# Default or base configuration for SE(3) diffusion experiments.

defaults:
  - override hydra/launcher: joblib

data:
  # CSV for path and metadata to training examples.
  csv_path: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/se3_processed_pdb/metadata.csv
  
  pdb_dir: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/pdb/
  temp_pdb_dir : /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/temp_pdb/

  mmcif_paths : /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/wangjun0198/workplace/cameo1/data/all_mmcif_paths.csv
  mmcif_dir: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/mmCIF/
  
  se3_processed_pdb_dir: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/se3_processed_pdb/
  
  esm_model_path : /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/wangjun0198/workplace/cameo1/.cache/torch/esmfold_3B_v1.pt
  esm_embed_dir : /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/esm_embed/

  energy_forces_dir: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/public/dataset/energy_forces/

  # omega_embed_dir: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/protein/workspace/jwang/static_prot_pred/dataset/omegafold_embed
  # valid_csv_path: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/protein/datasets/DFOLD_data/final_cameo_test_with_pkl.csv
  # val_gt_pdb_path:  /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/protein/workspace/chengkaihui/code/openfold-main/inference/2024.03.16/gt
  # fastfolding_data: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/protein/datasets/fast-folding/raw/fast-folding
  
  cluster_path: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/wangjun0198/workplace/cameo1/data/clusters-by-entity-30.txt
  
  filtering:
    max_len: 512
    min_len: 60
    # Selects a subset of examples. Useful for debugging.
    subset: null
    allowed_oligomer: [monomeric]
    max_helix_percent: 1.0
    max_loop_percent: 0.5
    min_beta_percent: -1.0
    rog_quantile: 0.96

  simulate:
    force_field: amber14-all.xml
    water_model: amber14/tip3pfb.xml
    implicit_solvent: implicit/gbn2.xml

  min_t: 0.01
  samples_per_eval_length: 4
  num_eval_lengths: 10
  num_t: 100

diffuser:
  diffuse_trans: True
  diffuse_rot: True

  # R(3) diffuser arguments
  r3:
    min_b: 0.1
    max_b: 20.0
    coordinate_scaling: 0.1

  # SO(3) diffuser arguments
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: False

model:
  esm_embed_size: 1024
  node_embed_size: 256
  edge_embed_size: 128
  dropout: 0.0
  embed:
    index_embed_size: 32
    aatype_embed_size: 64
    embed_self_conditioning: True
    num_bins: 22
    min_bin: 1e-5
    max_bin: 20.0
  ipa:
    c_embed: $(model.esm_embed_size)
    c_s: ${model.node_embed_size}
    c_z: ${model.edge_embed_size}
    c_hidden: 256
    c_skip: 64
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 4
    coordinate_scaling: ${diffuser.r3.coordinate_scaling}

experiment:
  # Experiment metadata
  name: baseline
  run_id: null

  #training mode
  use_ddp : True

  # Training arguments
  log_freq: 100
  batch_size: 256
  eval_batch_size: ${data.samples_per_eval_length}
  num_loader_workers: 5
  num_epoch: 500_000
  learning_rate: 0.0001
  max_squared_res: 500000
  prefetch_factor: 100
  use_gpu: True
  num_gpus: 3
  sample_mode: cluster_time_batch

  # Wandb logging
  wandb_dir: ./
  use_wandb: False

  # How many steps to checkpoint between.
  ckpt_freq: 10000
  # Take early checkpoint at step 100. Helpful for catching eval bugs early.
  early_ckpt: True

  # Checkpoint directory to warm start from.
  warm_start: null
#  warm_start: /cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/protein/workspace/jwang/static_prot_pred/cameo1/weights/best_weights.pth
  use_warm_start_conf: False
  ckpt_dir: ./ckpt/

  # Loss weights.
  trans_loss_weight: 1.0
  rot_loss_weight: 0.5
  rot_loss_t_threshold: 0.2
  separate_rot_loss: True
  trans_x0_threshold: 1.0
  coordinate_scaling: ${diffuser.r3.coordinate_scaling}
  bb_atom_loss_weight: 1.0
  bb_atom_loss_t_filter: 0.25
  dist_mat_loss_weight: 1.0
  dist_mat_loss_t_filter: 0.25
  aux_loss_weight: 0.25

  # Evaluation.
  eval_dir: ./eval_outputs
  noise_scale: 1.0
  # Filled in during training.
  num_parameters: null

hydra:
  sweeper:
    params:
      # Example of hydra multi run and wandb.
      experiment.name: use_wandb
      experiment.use_wandb: True
